deployment:
  role: control_plane
  role_control_plane:
    config_provider: etcd

apisix:
  node_listen:
    - __APISIX_NODE_LISTEN__
  ssl:
    enable: __APISIX_SSL_ENABLE__
    listen_port: __APISIX_SSL_LISTEN__
  enable_admin: true
  enable_control: false
  admin_key:
    - name: admin
      key: __APISIX_ADMIN_API_KEY__
      role: admin

etcd:
  host:
    - "__ETCD_HOST__"
  prefix: "/apisix"
  timeout: 30
  user: "__ETCD_USER__"
  password: "__ETCD_PASSWORD__"

plugins:
  - prometheus
  - jwt-auth
  - ip-restriction
  - cors
  - traffic-split
  - proxy-cache
  - openid-connect
  - serverless

nginx_config:
  worker_processes: "auto"
  error_log: "/usr/local/apisix/logs/error.log"
  access_log: "/usr/local/apisix/logs/access.log"

